services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbcars
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
