# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: bitnami/postgresql:latest
    shm_size: 128mb
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbcars
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
